- name: "APT - Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "apt-repository docker"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: "apt install aptitude apt-transport-https ca-certificates curl software-properties-common"
  apt:
    name: ['aptitude','apt-transport-https','ca-certificates','curl','software-properties-common']
    update_cache: yes
    state: present

- name: "apt install docker-ce, docker-compose"
  apt:
    name: ['docker-ce','docker-compose']
    update_cache: yes
    state: present
 
