- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_sis
  copy:
    src: files/sudoers_sis
    dest: /etc/sudoers.d/sis
    owner: root
    group: root
    mode: 0440
