- name: Password based logins are disabled - '^#?AuthenticationMethods'
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: '^#?AuthenticationMethods'
    line: 'AuthenticationMethods publickey'
    backup: yes

- name: Password based logins are disabled -'^#?PasswordAuthentication'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    backup: yes

- name: Password based logins are disabled - '^#?ChallengeResponseAuthentication'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    backup: yes

- name: Password based logins are disabled - '^#?PubkeyAuthentication'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    backup: yes

#  notify: restart_sshd
